#include <p16f18854.inc>
    
#ifdef BOOTLOADER
#define BLOFFSET 0x200
#else
__config _CONFIG1, _FEXTOSC_ECH & _RSTOSC_HFINT1 & _CSWEN_ON & _FCMEN_ON
__config _CONFIG2, _MCLRE_ON & _PWRTE_OFF & _LPBOREN_OFF & _BOREN_ON & _BORV_LO & _ZCD_OFF & _PPS1WAY_OFF & _STVREN_ON
__config _CONFIG3, _WDTCPS_WDTCPS_31 & _WDTE_SWDTEN & _WDTCWS_WDTCWS_7 & _WDTCCS_SC
__config _CONFIG4, _WRT_WRT_upper & _SCANE_not_available & _LVP_ON
__config _CONFIG5, _CP_OFF & _CPD_OFF
#define BLOFFSET 0
#endif
    
org BLOFFSET
RST     code    BLOFFSET
PAGESEL     MAIN
GOTO        MAIN

isr     code    0x04
BSF     0x7E, 0x0
MOVLP   0x0
MOVLW   0x2F
MOVLB   0x0
MOVWF   TMR0H
MOVLW   0x75
MOVWF   TMR0L
MOVLB   0xE
BCF     PORTA, 0x5
MOVLB   0x0
COMF    PORTC, F
BCF     0x7E, 0x0
RETFIE
code
MAIN

MOVLP 0x0
CALL SETUP
MOVLP 0x0
MOVLP 0x0
CALL LOOP
MOVLP 0x0
GOTO 0x31
MOVLP 0x0
GOTO 0x11

SETUP
    MOVLB 0x1E
    CLRF 0x4E
    MOVLB 0x0
    CLRF LATC
    CLRF TRISC
    CLRF PORTC
    BSF INTCON, 0x7
    BCF INTCON, 0x6
    BSF INTCON, 0x0
    MOVLB 0xE
    BSF LATA, 0x5
    MOVLW 0xD3
    MOVLB 0x0
    MOVWF T0CON0
    MOVLW 0x41
    MOVWF T0CON1
    MOVLW 0x2F
    MOVWF TMR0H
    MOVLW 0x75
    MOVWF TMR0L
    MOVLB 0xE
    BCF PORTA, 0x5
RETURN


LOOP
    RETURN

end